import type { Metadata } from "next";

import { site } from "@/content/site";
import { ogImageSize } from "@/lib/og-image-size";

export const absoluteUrl = (path: string) => new URL(path, site.url).toString();

/** Share image for pages without their own; generated by src/app/og/[image]/route.tsx. */
export const defaultShareImage = { url: "/og/home.png", alt: `${site.name}: ${site.tagline}` };

interface PageSeo {
  title: string;
  description: string;
  /** Site-relative path with trailing slash, e.g. "/apps/". Used for the canonical URL. */
  path: string;
  type?: "website" | "article";
  publishedTime?: string;
  authors?: string[];
  image?: { url: string; alt: string };
}

/**
 * Complete per-page metadata. Next.js replaces (rather than merges) nested objects such as
 * `openGraph`, so every page passes through here to keep canonical, Open Graph and Twitter
 * tags consistent.
 */
export function pageMetadata({
  title,
  description,
  path,
  type = "website",
  publishedTime,
  authors,
  image = defaultShareImage,
}: PageSeo): Metadata {
  const images = [{ ...image, ...ogImageSize, type: "image/png" }];

  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type,
      url: path,
      siteName: site.name,
      locale: "en_US",
      title,
      description,
      images,
      ...(type === "article" ? { publishedTime, authors } : {}),
    },
    twitter: { card: "summary_large_image", title, description, images },
  };
}
